// seed portfolio data (JS)
import Logo from "../assets/img/profile/Logo.png";

export const seedData = {
  profile: {
    name: "Akekaphol Ramkaew",
    title: "Full-Stack Developer & Automation IOT Engineer",
    bio: "Passionate about crafting Automation system, IOT and Web applications , Performant web experiences that solve real problems. I specialize in React, JavaScript,PLC ,IOT , and web applications.",
    avatarUrl: Logo,
    location: "Songkhla, Thailand",
    socials: [
      { type: "github", url: "https://github.com" },
      { type: "linkedin", url: "https://linkedin.com" },
      { type: "x", url: "https://x.com" },
      { type: "email", url: "mailto:alex@example.com" }
    ],
    cvUrl: "/cv.pdf",
    skills: ["React", "JavaScript", "Node.js", "Tailwind CSS", "MongoDB", "PLC Siements", "Siements IoT","PLC Mitsubishi","HMI Samkoon","Arduino Boards"]
  },
  categories: ["Webapp", "Automation", "IOT"],
  tags: ["React", "JavaScript", "Node.js", "Tailwind CSS", "MongoDB", "UI/UX", "Automation", "IOT"],
  projects: [
    {
      id: "p-001",
      slug: "ecommerce-dashboard",
      title: "E-Commerce Dashboard",
      year: 2024,
      summary: "Real-time analytics dashboard for tracking KPIs, sales metrics, and customer behavior across multiple channels.",
      cover: "/placeholder.svg",
      gallery: ["/placeholder.svg", "/placeholder.svg"],
      categories: ["Web"],
      tags: ["React", "Vite", "Tailwind", "Charts"],
      techStack: ["React", "TypeScript", "Vite", "Tailwind CSS", "Recharts", "Socket.IO"],
      role: "Lead Front-End Developer",
      teamSize: 4,
      status: "Shipped",
      problemMd: "## The Problem\n\nOur client needed a unified view...",
      approachMd: "## Our Approach\n\nWe designed a custom dashboard...",
      outcomeMd: "## The Outcome\n\n✅ 80% reduction in time...",
      links: { demo: "https://demo.example.com", repo: "https://github.com/example/dashboard" },
      featured: true
    },
    {
      id: "p-002",
      slug: "fitness-mobile-app",
      title: "Fitness Tracking Mobile App",
      year: 2024,
      summary: "Cross-platform mobile app...",
      cover: "/placeholder.svg",
      gallery: ["/placeholder.svg"],
      categories: ["Mobile"],
      tags: ["React Native", "Firebase", "AI"],
      techStack: ["React Native", "Expo", "Firebase", "TensorFlow.js"],
      role: "Full-Stack Developer",
      teamSize: 3,
      status: "In Progress",
      problemMd: "## The Problem\n\nFitness enthusiasts struggle...",
      approachMd: "## Our Approach\n\nWe built a streamlined...",
      outcomeMd: "## The Outcome\n\nCurrently in beta testing...",
      links: { repo: "https://github.com/example/fitness" },
      featured: true
    },
    {
      id: "p-003",
      slug: "design-system",
      title: "Corporate Design System",
      year: 2023,
      summary: "Comprehensive design system...",
      cover: "/placeholder.svg",
      gallery: ["/placeholder.svg"],
      categories: ["UI/UX", "Web"],
      tags: ["Design System", "Storybook", "React"],
      techStack: ["React", "TypeScript", "Storybook", "Tailwind CSS"],
      role: "UI Engineer",
      teamSize: 2,
      status: "Shipped",
      problemMd: "## The Problem\n\nInconsistent UI patterns...",
      approachMd: "## Our Approach\n\nCreated a unified design system...",
      outcomeMd: "## The Outcome\n\nAdopted across 15 teams...",
      links: { demo: "https://storybook.example.com", repo: "https://github.com/example/design-system" },
      featured: true
    },
    {
      id: "p-004",
      slug: "open-source-cli",
      title: "Developer CLI Tool",
      year: 2023,
      summary: "Command-line tool...",
      cover: "/placeholder.svg",
      gallery: [],
      categories: ["Open Source"],
      tags: ["Node.js", "CLI", "TypeScript"],
      techStack: ["Node.js", "TypeScript", "Commander.js"],
      role: "Creator & Maintainer",
      teamSize: 1,
      status: "Active",
      problemMd: "## The Problem\n\nRepetitive setup tasks...",
      approachMd: "## Our Approach\n\nBuilt an extensible CLI...",
      outcomeMd: "## The Outcome\n\n2,000+ GitHub stars...",
      links: { repo: "https://github.com/example/cli-tool" },
      featured: false
    }
  ],
  messages: []
};
